[package]
name = "rs-fsrs-c"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
fsrs = { git = "https://github.com/open-spaced-repetition/rs-fsrs" }

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.27.0"
